import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Import your custom components
import Header from "@/app/components/Header";  // Ensure the path is correct
import Footer from "./components/footer";
import Anouce from "./components/Anouncement";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Anouce/>  {/* Ensure that Anoun is imported correctly */}
        <Header />  {/* Ensure that Header is imported correctly */}
        {children}
        <Footer/> {/* Ensure that Footer is imported correctly */}
      </body>
    </html>
  );
}
